# 有効設定
JoinCheck: true # 入室権限チェック
AutoOP: true # 自動op付与
SendOPMessage: true # 入退室メッセージ切り替え

# prefix
Prefix: '&e[ななみ鯖]'

# 入室権限設定
ServerJoinPermList: 'Admin'
ServerJoinPlayerList: '7mi_chan'

# 付与設定
ServerOPPermList: 'Admin,Moderator'
ServerOPPlayerList: 'Yotuba_Nakano,c6f2f6d3-5a7d-45cd-a16a-52e4d4e2ceb2'

# MySQL
MySQLServer: ''
MySQLPort: 3306
MySQLDatabase: ''
MySQLUsername: ''
MySQLPassword: ''
MySQLOption: '?allowPublicKeyRetrieval=true&useSSL=false'