name: NanamiPlayerSystem
version: '${version}'
main: xyz.n7mn.dev.nanamiplayersystem.NanamiPlayerSystem
authors: [ 7mi_chan ]
description: NanamiPlayerSystem
depend: [ViaVersion]
commands:
  perm:
    description: ''
    usage: '/perm'
  join:
    description: ''
    usage: '/join'
